// Generated by CoffeeScript 1.12.7
(function() {
  var coffee;

  coffee = function(message) {
    var answer;
    if (message == null) {
      message = "Ready for some coffee?";
    }
    answer = confirm(message);
    return "Your answer is " + answer;
  };

  alert("You said " + (coffee()));

}).call(this);
